# ============================================================
# Docker Compose — Cloud App (Project: Antick Async)
# ============================================================

services:
  # ==================== DATABASE ====================
  db:
    image: postgres:16
    container_name: antick-async-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: cloudapp
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - cloudnet
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d cloudapp"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  # ==================== BACKEND ====================
  backend:
    image: notyourkisee/antick-async-backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: antick-async-backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    networks:
      - cloudnet
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

  # ==================== FRONTEND ====================
  frontend:
    image: notyourkisee/antick-async-frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        # VITE_API_URL: https://api.antick-async.online
        VITE_API_URL: http://localhost:8000  #ini untuk development lokal, jangan lupa ganti ke URL produksi saat deploy
        VITE_SPLINE_SCENE_URL: https://prod.spline.design/JtAnJNdegVMirBAb/scene.splinecode
        VITE_SPLINE_SCENE_URL_REGISTER: https://prod.spline.design/D4gusWP1Rw4kgtey/scene.splinecode
    container_name: antick-async-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    networks:
      - cloudnet
    depends_on:
      - backend


# ==================== CLOUDFLARE TUNNEL ====================
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: antick-async-tunnel
    restart: unless-stopped
    env_file:
      - .env
    command: tunnel --no-autoupdate run
    networks:
      - cloudnet
    depends_on:
      - frontend
      - backend

# ==================== VOLUMES ====================
volumes:
  pgdata:
    name: cloudapp-pgdata

# ==================== NETWORKS ====================
networks:
  cloudnet:
    name: cloudapp-network
    driver: bridge
