[pytest]
testpaths = tests
python_files = test_*.py
python_functions = test_*
addopts = -v --tb=short
filterwarnings =
    ; Suppress DeprecationWarning dari python-jose (datetime.utcnow)
    ; Library issue: https://github.com/mpdavis/python-jose/issues/332
    ignore::DeprecationWarning:jose
    ; Suppress PendingDeprecationWarning dari starlette (import multipart)
    ignore::PendingDeprecationWarning:starlette